/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TacSafetyRouteImport } from './routes/tac-safety'
import { Route as ProphylaxisRouteImport } from './routes/prophylaxis'
import { Route as EdMigraineRouteImport } from './routes/ed-migraine'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'

const TacSafetyRoute = TacSafetyRouteImport.update({
  id: '/tac-safety',
  path: '/tac-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphylaxisRoute = ProphylaxisRouteImport.update({
  id: '/prophylaxis',
  path: '/prophylaxis',
  getParentRoute: () => rootRouteImport,
} as any)
const EdMigraineRoute = EdMigraineRouteImport.update({
  id: '/ed-migraine',
  path: '/ed-migraine',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/ed-migraine': typeof EdMigraineRoute
  '/prophylaxis': typeof ProphylaxisRoute
  '/tac-safety': typeof TacSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/ed-migraine': typeof EdMigraineRoute
  '/prophylaxis': typeof ProphylaxisRoute
  '/tac-safety': typeof TacSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/ed-migraine': typeof EdMigraineRoute
  '/prophylaxis': typeof ProphylaxisRoute
  '/tac-safety': typeof TacSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/ed-migraine'
    | '/prophylaxis'
    | '/tac-safety'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostic' | '/ed-migraine' | '/prophylaxis' | '/tac-safety'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/ed-migraine'
    | '/prophylaxis'
    | '/tac-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  EdMigraineRoute: typeof EdMigraineRoute
  ProphylaxisRoute: typeof ProphylaxisRoute
  TacSafetyRoute: typeof TacSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tac-safety': {
      id: '/tac-safety'
      path: '/tac-safety'
      fullPath: '/tac-safety'
      preLoaderRoute: typeof TacSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophylaxis': {
      id: '/prophylaxis'
      path: '/prophylaxis'
      fullPath: '/prophylaxis'
      preLoaderRoute: typeof ProphylaxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ed-migraine': {
      id: '/ed-migraine'
      path: '/ed-migraine'
      fullPath: '/ed-migraine'
      preLoaderRoute: typeof EdMigraineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  EdMigraineRoute: EdMigraineRoute,
  ProphylaxisRoute: ProphylaxisRoute,
  TacSafetyRoute: TacSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
